#!/bin/bash
# Build "Ember Mug.app" — a menu-bar-only bundle that launches ember_mug_app.py
# with a Python that has rumps + python-ember-mug installed.
#
#   ./build_app.sh                # auto-detect Python (pipx venv, ./.venv, or python3)
#   EMBER_MUG_PYTHON=/path/to/python ./build_app.sh
#   ./build_app.sh --launch       # build, then open the app

set -e

APP_NAME="Ember Mug"
BUNDLE_ID="com.gwhillhouse.ember-mug"
APP_DIR="$HOME/Applications/$APP_NAME.app"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
LOG_DIR="$HOME/Library/Logs/EmberMug"
PYTHON_BIN="${EMBER_MUG_PYTHON:-}"

echo "🫖 Building $APP_NAME.app"

# --- pick a Python that can actually run the app -----------------------------
candidates=(
    "$PYTHON_BIN"
    "$SCRIPT_DIR/.venv/bin/python"
    "$HOME/.local/pipx/venvs/python-ember-mug/bin/python"
    "$(command -v python3 || true)"
)
PYTHON_BIN=""
for candidate in "${candidates[@]}"; do
    [ -n "$candidate" ] && [ -x "$candidate" ] || continue
    if "$candidate" -c 'import rumps, ember_mug, objc, WebKit' >/dev/null 2>&1; then
        PYTHON_BIN="$candidate"
        break
    fi
done

if [ -z "$PYTHON_BIN" ]; then
    echo "❌ No Python found with rumps + python-ember-mug installed."
    echo
    echo "   Easiest fix (creates ./.venv):"
    echo "     uv venv && uv pip install 'rumps>=0.4.0' 'python-ember-mug>=1.2.1'"
    echo
    echo "   Or point at one you already have:"
    echo "     EMBER_MUG_PYTHON=/path/to/python ./build_app.sh"
    exit 1
fi
echo "   Python: $PYTHON_BIN ($("$PYTHON_BIN" --version 2>&1))"

# --- bundle ------------------------------------------------------------------
pkill -f "ember_mug_app.py" 2>/dev/null || true
rm -rf "$APP_DIR"
mkdir -p "$APP_DIR/Contents/MacOS" "$APP_DIR/Contents/Resources" "$LOG_DIR"

cat > "$APP_DIR/Contents/Info.plist" <<PLISTEOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key>          <string>ember-launcher</string>
    <key>CFBundleIdentifier</key>          <string>$BUNDLE_ID</string>
    <key>CFBundleName</key>                <string>$APP_NAME</string>
    <key>CFBundleDisplayName</key>         <string>$APP_NAME</string>
    <key>CFBundlePackageType</key>         <string>APPL</string>
    <key>CFBundleShortVersionString</key>  <string>2.0.0</string>
    <key>CFBundleVersion</key>             <string>2</string>
    <key>LSMinimumSystemVersion</key>      <string>12.0</string>
    <key>LSUIElement</key>                 <true/>
    <key>NSHighResolutionCapable</key>     <true/>
    <key>NSBluetoothAlwaysUsageDescription</key>
    <string>Ember Mug connects to your mug over Bluetooth to show its temperature and battery.</string>
</dict>
</plist>
PLISTEOF

cat > "$APP_DIR/Contents/MacOS/ember-launcher" <<LAUNCHEREOF
#!/bin/bash
# Generated by build_app.sh.
# Starts Python detached and exits. (Do NOT exec Python here: on recent macOS a
# script-bundle that execs a foreign binary gets a status item that never draws.)
export EMBER_MUG_LAUNCHER="\$0"
cd "$SCRIPT_DIR"
mkdir -p "$LOG_DIR"
pkill -f "ember_mug_app.py" 2>/dev/null
sleep 0.3
nohup "$PYTHON_BIN" -u "$SCRIPT_DIR/ember_mug_app.py" >> "$LOG_DIR/launcher.log" 2>&1 &
disown
exit 0
LAUNCHEREOF
chmod +x "$APP_DIR/Contents/MacOS/ember-launcher"

echo "✅ Built: $APP_DIR"
echo "   Log:   $LOG_DIR/ember-mug.log"
echo
echo "Launch:  open \"$APP_DIR\""
echo "Login:   use 'Start at Login' in the app's menu"

if [ "$1" = "--launch" ]; then
    open "$APP_DIR"
    echo "🚀 Launched"
fi
